name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: python manage.py test
      
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/vm-management-backend:${{ github.sha }} .
      
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/vm-management-backend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG" | base64 --decode > ~/.kube/config
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml