# Generated by Django 5.1.1 on 2024-09-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
