# Generated by Django 5.1.1 on 2024-09-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='cpu',
            field=models.CharField(default='2 vCPUs', max_length=50),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ram',
            field=models.CharField(default='4 GB', max_length=50),
        ),
    ]
