# Generated by Django 5.1.1 on 2024-09-22 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_virtualmachine_cost_virtualmachine_cpu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssignedVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.virtualmachine')),
            ],
            options={
                'unique_together': {('new_owner', 'vm')},
            },
        ),
    ]
