# Generated by Django 5.1.1 on 2024-09-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_subuser_assigned_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='bill',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='backup',
            name='status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='unbacked_data',
            field=models.FloatField(default=1.0),
        ),
    ]
